#server.port=8082
#spring.application.name=demo
#spring.mongodb.uri=mongodb+srv://mayonesa:apvx@cluster0.jpdftgu.mongodb.net/test?retryWrites=true&w=majority

server.port=8082
spring.application.name=demo

# Para que la librería de Spring Data no truene al compilar
spring.data.mongodb.uri=mongodb+srv://mayonesa:apvx@cluster0.jpdftgu.mongodb.net/test?retryWrites=true&w=majority

# Para que el starter nuevo de Spring Boot 3 lo reconozca directo
spring.mongodb.uri=mongodb+srv://mayonesa:apvx@cluster0.jpdftgu.mongodb.net/test?retryWrites=true&w=majority
